on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Build static content
      run: CI= yarn run build

    - name: Change directory to build
      run: cd dist
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: tigras.serveriai.lt
        username: ci_band-suggester@tamulaitis.lt
        password: ${{ secrets.ftp_password }}
        local-dir: ./dist/
        server-dir: ./